extends:
  - '@dudeofawesome/browser'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:jsx-a11y/recommended'

settings:
  react:
    version: 'detect'

rules:
  # limit max element nesting to reduce component complexity
  react/jsx-max-depth:
    - 'error'
    - max: 5

  # prefer ES6 classes
  react/prefer-es6-class: 'error'

  # prefer functional components
  react/prefer-stateless-function: 'error'

  react/no-children-prop: 'off'

  react/jsx-key: 'error'
