root: true
extends:
  - '@dudeofawesome'
  - '@dudeofawesome/cli'
  - '@dudeofawesome/jest'
  - '@dudeofawesome/typescript'
  - '@dudeofawesome/esmodule'
ignorePatterns:
  - '**/test/*/**'

overrides:
  - files:
      - 'scripts/bump.ts'
      - 'scripts/concurrently-ws.ts'
    rules:
      n/shebang: 'off'
