root: true
extends:
  - '@dudeofawesome'
  - '@dudeofawesome/cli'
  - '@dudeofawesome/jest'
  - '@dudeofawesome/typescript'
parserOptions:
  ecmaVersion: 2022

overrides:
  - files:
      - '**/test/**'
      - '**/__test__/**'
      - '*.test.*'
      - '*.spec.*'
      - '*.unit.*'
      - '*.e2e.*'
    rules:
      n/no-process-env: 'off'
