root: true
extends:
  - '@dudeofawesome/eslint-config'
  - '@dudeofawesome/eslint-config-node'
  - '@dudeofawesome/eslint-config-cli'
  - '@dudeofawesome/eslint-config-jest'
  - '@dudeofawesome/eslint-config-typescript'
  - '@dudeofawesome/eslint-config-esmodule'
ignorePatterns:
  - '**/test/*/**'

overrides:
  - files:
      - 'scripts/bump.ts'
      - 'scripts/concurrently-ws.ts'
    rules:
      n/shebang: 'off'
