root: true
extends:
  - '@code-style/eslint-config'
  - '@code-style/eslint-config-node'
  - '@code-style/eslint-config-cli'
  - '@code-style/eslint-config-jest'
  - '@code-style/eslint-config-typescript'
  - '@code-style/eslint-config-esmodule'
ignorePatterns:
  - '**/test/*/**'
  - 'packages/code-style'
  - 'packages/create-configs'
  - 'packages/eslint-config-typescript'
  - 'packages/eslint-plugin-nest'
  - 'packages/jest-configs'
  - 'utils'

overrides:
  - files:
      - 'scripts/bump.ts'
      - 'scripts/concurrently-ws.ts'
    rules:
      n/shebang: 'off'
