overrides:
  - files:
      - '**/test/**'
      - '**/__test__/**'
      - '*.test.*'
      - '*.spec.*'
      - '*.unit.*'
      - '*.e2e.*'
    extends:
      - 'plugin:jest/recommended'
    settings:
      jest:
        version: 'detect'
    # TODO(0): support tsconfig.test.json

    rules:
      # prevent return statements in tests
      jest/no-test-return-statement: 'error'

      # use jest comparators instead of comparing booleans
      jest/prefer-comparison-matcher: 'error'
      jest/prefer-equality-matcher: 'error'

      # use expect(foo()).resolve instead of expect(await foo())
      jest/prefer-expect-resolves: 'error'

      # require hooks to be inside a describe
      jest/require-top-level-describe: 'error'

      # prevent error from dev deps in tests
      n/no-unpublished-import: 'off'

      # allow test files of any length
      max-lines: 'off'

      # don't require dot notation in tests as this can be useful for accessing
      #   Typescript private properties & methods
      dot-notation: 'off'
      '@typescript-eslint/dot-notation': 'off'

      # allow `any`
      '@typescript-eslint/no-explicit-any': 'off'
      '@typescript-eslint/no-unsafe-return': 'off'
      '@typescript-eslint/no-unsafe-assignment': 'off'
      '@typescript-eslint/no-unsafe-member-access': 'off'
      '@typescript-eslint/no-unsafe-argument': 'off'

      # allow non-null assertions
      '@typescript-eslint/no-non-null-assertion': 'off'
      '@typescript-eslint/no-non-null-asserted-optional-chain': 'off'

      # simplify testing methods
      '@typescript-eslint/unbound-method': 'off'
