overrides:
  - files:
      - '**/test/**'
      - '**/__test__/**'
      - '*.test.*'
      - '*.spec.*'
      - '*.unit.*'
      - '*.e2e.*'
    extends:
      - 'plugin:jest/recommended'
    settings:
      jest:
        version: 'detect'
    # TODO(0): support tsconfig.test.json

    rules:
      # prevent return statements in tests
      jest/no-test-return-statement: 'error'

      # use jest comparators instead of comparing booleans
      jest/prefer-comparison-matcher: 'error'
      jest/prefer-equality-matcher: 'error'

      # use expect(foo()).resolve instead of expect(await foo())
      jest/prefer-expect-resolves: 'error'

      # require hooks to be inside a describe
      jest/require-top-level-describe: 'error'

      # prevent error from dev deps in tests
      'n/no-unpublished-import': 'off'
