extends:
  - 'plugin:@dudeofawesome/eslint-plugin-nest/recommended'
  - '@dudeofawesome/eslint-config-node'
  - '@dudeofawesome/eslint-config-typescript'

rules:
  # Disallow importing files from `@nestjs/terminus` since it includes a bunch of incorrect types.
  no-restricted-imports:
    - 'error'
    - patterns:
        - '@nestjs/terminus/dist/*'
