plugins:
  - 'eslint-plugin-import'

parserOptions:
  sourceType: 'module'

rules:
  # Disallow commonjs modules.
  import/no-commonjs: 'error'

  # Turn off the `import` ban from `@dudeofawesome/eslint-config/rule-sets/imports.yaml`
  no-restricted-syntax: 'off'
