extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@shopify/typescript'
  - 'plugin:import/typescript'
  - 'plugin:prettier/recommended'
plugins:
  - '@typescript-eslint'

parser: '@typescript-eslint/parser'

rules:
  prettier/prettier: 'warn'
  '@typescript-eslint/no-inferrable-types': 'off'
  '@typescript-eslint/no-unused-vars':
    ['warn', { args: 'none', destructuredArrayIgnorePattern: '^_' }]
  '@typescript-eslint/no-use-before-define': 'error'
