extends:
  - 'plugin:@typescript-eslint/recommended'
plugins:
  - '@typescript-eslint'

rules:
  prettier/prettier: 'warn'
  '@typescript-eslint/no-inferrable-types': 'off'
  '@typescript-eslint/no-unused-vars':
    ['warn', { args: 'none', destructuredArrayIgnorePattern: '^_' }]
  '@typescript-eslint/no-use-before-define': 'error'

settings:
  'import/resolver':
    typescript:
