extends:
  - 'plugin:@typescript-eslint/strict'
  # - 'plugin:@shopify/typescript'
  - 'plugin:import/typescript'

parserOptions:
  project: true

rules:
  '@typescript-eslint/no-inferrable-types': 'off'
  '@typescript-eslint/no-unused-vars':
    ['warn', { args: 'none', destructuredArrayIgnorePattern: '^_' }]
  '@typescript-eslint/naming-convention': 'off'
  '@shopify/binary-assignment-parens': 'off'
