extends:
  - '@dudeofawesome/eslint-config-react'
  - 'plugin:@next/eslint-plugin-next/recommended'

rules:
  # NextJS requires page components to be default exports
  import/no-default-export: 'off'
