extends:
  - 'plugin:@dudeofawesome/nest/recommended'
  - '@dudeofawesome/node'
  - '@dudeofawesome/typescript'

rules:
  # Disallow importing files from `@nestjs/terminus` since it includes a bunch of incorrect types.
  no-restricted-imports:
    - 'error'
    - patterns:
        - '@nestjs/terminus/dist/*'
