extends:
  - 'plugin:@dudeofawesome/nest/recommended'
  - '@dudeofawesome/node'
  - '@dudeofawesome/typescript'

rules:
  no-restricted-imports:
    - 'error'
    - patterns:
        - '@nestjs/terminus/dist/*'
