extends:
  - 'plugin:@shopify/esnext'
  - 'plugin:prettier/recommended'
plugins:
  - 'jest'
parserOptions:
  ecmaVersion: 2022 # Version is inline with Node 16
env:
  jest/globals: yes

rules:
  prettier/prettier: 'warn'
  node/exports-style: 'off'
  line-comment-position: 'off'
  no-warning-comments: 'warn'
  require-atomic-updates: 'warn'
  no-negated-condition: 'off'
