extends:
  - 'plugin:@shopify/esnext'
  - 'plugin:prettier/recommended'
plugins:
  - 'jest'
parserOptions:
  ecmaVersion: 2022 # Version is inline with Node 16
env:
  jest/globals: yes

rules:
  '@babel/new-cap': 'off'
  id-length: 'off'
  import/order:
    - 'warn'
    - groups:
        - 'builtin'
        - 'external'
        - 'internal'
  line-comment-position: 'off'
  no-empty-function: 'warn'
  no-negated-condition: 'off'
  no-nested-ternary: 'off'
  no-warning-comments: 'warn'
  node/exports-style: 'warn'
  prettier/prettier: 'warn'
  require-atomic-updates: 'warn'
  sort-class-members/sort-class-members: 'off'
