extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:promise/recommended'
  - 'plugin:import/recommended'
  - 'plugin:@eslint-community/eslint-comments/recommended'

  - './rules/bugs.yaml'
  - './rules/deprecated.yaml'
  - './rules/footguns.yaml'
  - './rules/imports.yaml'
  - './rules/miscellaneous.yaml'
  - './rules/modern-code.yaml'
  - './rules/promises.yaml'
  - './rules/readability.yaml'
  - './rules/security.yaml'

plugins:
  - 'json-files'

parserOptions:
  ecmaVersion: 2022 # Version is inline with Node 16
  sourceType: 'module'

ignorePatterns:
  - '**/dist/**'
