# yaml-language-server: $schema=https://github.com/dudeofawesome/code-style/releases/download/v2.0.0-30/codestylerc.schema.json

version: 2.0.0-30
project_type: cli
languages:
  - ts
runtime: nodejs
builder: esbuild
input_dir: src
output_dir: dist
technologies:
  - esm
library: true
lenient: false
overwrite: true
