extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:promise/recommended'
  # TODO(0): consider switching to `eslint-plugin-i`
  - 'plugin:import/recommended'
  - 'plugin:@eslint-community/eslint-comments/recommended'

  - './rule-sets/bugs.yaml'
  - './rule-sets/deprecated.yaml'
  - './rule-sets/footguns.yaml'
  - './rule-sets/imports.yaml'
  - './rule-sets/miscellaneous.yaml'
  - './rule-sets/modern-code.yaml'
  - './rule-sets/promises.yaml'
  - './rule-sets/readability.yaml'
  - './rule-sets/security.yaml'

plugins:
  - 'json-files'

parserOptions:
  ecmaVersion: 2022 # Version is inline with Node 16
  sourceType: 'module'

env:
  commonjs: true

ignorePatterns:
  - '**/dist/**'
