root: true
extends:
  - '@dudeofawesome'
  - '@dudeofawesome/cli'
parserOptions:
  ecmaVersion: 2022

overrides:
  # - files:
  #     - 'bin/**'
  - files:
      - 'src/**'
    extends:
      - '@dudeofawesome/typescript'
