root: true
extends:
  - '@code-style'
  - '@code-style/node'
  - '@code-style/esmodule'
  - '@code-style/typescript'

ignorePatterns:
  - '/prettierrc.*'
  - '/config-types.*'

rules:
  import/no-default-export: 'off'
  n/no-sync: 'off'
