root: true
extends:
  - '@dudeofawesome'
  - '@dudeofawesome/node'
  - '@dudeofawesome/esmodule'
  - '@dudeofawesome/typescript'

ignorePatterns:
  - '/prettierrc.*'

rules:
  import/no-default-export: 'off'
  n/no-sync: 'off'
